server:
  port: 8080

spring:
  application:
    name: animal-shop

  jackson:
    default-property-inclusion: NON_NULL

  data:
    mongodb:
      uri: mongodb://${MONGODB_USER}:${MONGODB_PW}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DB}?authSource=admin&replicaSet=replset&ssl=true

---

spring:
  profiles: local

  data:
    mongodb:
      uri: mongodb://localhost:27017/animal-shop?readPreference=primary&ssl=false